// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Author         string
	AuthorOfNovel  string
	Chapter        string
	ChapterOfNovel string
	ChapterQueue   string
	Cover          string
	Genre          string
	GenreOfNovel   string
	Group          string
	Language       string
	Novel          string
	NovelQueue     string
	NovelType      string
	Tag            string
	TagOfNovel     string
}{
	Author:         "author",
	AuthorOfNovel:  "author_of_novel",
	Chapter:        "chapter",
	ChapterOfNovel: "chapter_of_novel",
	ChapterQueue:   "chapter_queue",
	Cover:          "cover",
	Genre:          "genre",
	GenreOfNovel:   "genre_of_novel",
	Group:          "group",
	Language:       "language",
	Novel:          "novel",
	NovelQueue:     "novel_queue",
	NovelType:      "novel_type",
	Tag:            "tag",
	TagOfNovel:     "tag_of_novel",
}
