// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Cover is an object representing the database table.
type Cover struct {
	ID         int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	URL        string      `boil:"url" json:"url" toml:"url" yaml:"url"`
	Downloaded null.Bool   `boil:"downloaded" json:"downloaded,omitempty" toml:"downloaded" yaml:"downloaded,omitempty"`
	Path       null.String `boil:"path" json:"path,omitempty" toml:"path" yaml:"path,omitempty"`

	R *coverR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L coverL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CoverColumns = struct {
	ID         string
	URL        string
	Downloaded string
	Path       string
}{
	ID:         "id",
	URL:        "url",
	Downloaded: "downloaded",
	Path:       "path",
}

// Generated where

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var CoverWhere = struct {
	ID         whereHelperint
	URL        whereHelperstring
	Downloaded whereHelpernull_Bool
	Path       whereHelpernull_String
}{
	ID:         whereHelperint{field: `id`},
	URL:        whereHelperstring{field: `url`},
	Downloaded: whereHelpernull_Bool{field: `downloaded`},
	Path:       whereHelpernull_String{field: `path`},
}

// CoverRels is where relationship names are stored.
var CoverRels = struct {
	Novels string
}{
	Novels: "Novels",
}

// coverR is where relationships are stored.
type coverR struct {
	Novels NovelSlice
}

// NewStruct creates a new relationship struct
func (*coverR) NewStruct() *coverR {
	return &coverR{}
}

// coverL is where Load methods for each relationship are stored.
type coverL struct{}

var (
	coverColumns               = []string{"id", "url", "downloaded", "path"}
	coverColumnsWithoutDefault = []string{"url", "path"}
	coverColumnsWithDefault    = []string{"id", "downloaded"}
	coverPrimaryKeyColumns     = []string{"id"}
)

type (
	// CoverSlice is an alias for a slice of pointers to Cover.
	// This should generally be used opposed to []Cover.
	CoverSlice []*Cover
	// CoverHook is the signature for custom Cover hook methods
	CoverHook func(context.Context, boil.ContextExecutor, *Cover) error

	coverQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	coverType                 = reflect.TypeOf(&Cover{})
	coverMapping              = queries.MakeStructMapping(coverType)
	coverPrimaryKeyMapping, _ = queries.BindMapping(coverType, coverMapping, coverPrimaryKeyColumns)
	coverInsertCacheMut       sync.RWMutex
	coverInsertCache          = make(map[string]insertCache)
	coverUpdateCacheMut       sync.RWMutex
	coverUpdateCache          = make(map[string]updateCache)
	coverUpsertCacheMut       sync.RWMutex
	coverUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var coverBeforeInsertHooks []CoverHook
var coverBeforeUpdateHooks []CoverHook
var coverBeforeDeleteHooks []CoverHook
var coverBeforeUpsertHooks []CoverHook

var coverAfterInsertHooks []CoverHook
var coverAfterSelectHooks []CoverHook
var coverAfterUpdateHooks []CoverHook
var coverAfterDeleteHooks []CoverHook
var coverAfterUpsertHooks []CoverHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Cover) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Cover) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Cover) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Cover) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Cover) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Cover) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Cover) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Cover) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Cover) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range coverAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCoverHook registers your hook function for all future operations.
func AddCoverHook(hookPoint boil.HookPoint, coverHook CoverHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		coverBeforeInsertHooks = append(coverBeforeInsertHooks, coverHook)
	case boil.BeforeUpdateHook:
		coverBeforeUpdateHooks = append(coverBeforeUpdateHooks, coverHook)
	case boil.BeforeDeleteHook:
		coverBeforeDeleteHooks = append(coverBeforeDeleteHooks, coverHook)
	case boil.BeforeUpsertHook:
		coverBeforeUpsertHooks = append(coverBeforeUpsertHooks, coverHook)
	case boil.AfterInsertHook:
		coverAfterInsertHooks = append(coverAfterInsertHooks, coverHook)
	case boil.AfterSelectHook:
		coverAfterSelectHooks = append(coverAfterSelectHooks, coverHook)
	case boil.AfterUpdateHook:
		coverAfterUpdateHooks = append(coverAfterUpdateHooks, coverHook)
	case boil.AfterDeleteHook:
		coverAfterDeleteHooks = append(coverAfterDeleteHooks, coverHook)
	case boil.AfterUpsertHook:
		coverAfterUpsertHooks = append(coverAfterUpsertHooks, coverHook)
	}
}

// One returns a single cover record from the query.
func (q coverQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Cover, error) {
	o := &Cover{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for cover")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Cover records from the query.
func (q coverQuery) All(ctx context.Context, exec boil.ContextExecutor) (CoverSlice, error) {
	var o []*Cover

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Cover slice")
	}

	if len(coverAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Cover records in the query.
func (q coverQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count cover rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q coverQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if cover exists")
	}

	return count > 0, nil
}

// Novels retrieves all the novel's Novels with an executor.
func (o *Cover) Novels(mods ...qm.QueryMod) novelQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ste\".\"novel\".\"cover_id\"=?", o.ID),
	)

	query := Novels(queryMods...)
	queries.SetFrom(query.Query, "\"ste\".\"novel\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"ste\".\"novel\".*"})
	}

	return query
}

// LoadNovels allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (coverL) LoadNovels(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCover interface{}, mods queries.Applicator) error {
	var slice []*Cover
	var object *Cover

	if singular {
		object = maybeCover.(*Cover)
	} else {
		slice = *maybeCover.(*[]*Cover)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &coverR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &coverR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`ste.novel`), qm.WhereIn(`cover_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load novel")
	}

	var resultSlice []*Novel
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice novel")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on novel")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for novel")
	}

	if len(novelAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Novels = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &novelR{}
			}
			foreign.R.Cover = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CoverID) {
				local.R.Novels = append(local.R.Novels, foreign)
				if foreign.R == nil {
					foreign.R = &novelR{}
				}
				foreign.R.Cover = local
				break
			}
		}
	}

	return nil
}

// AddNovels adds the given related objects to the existing relationships
// of the cover, optionally inserting them as new records.
// Appends related to o.R.Novels.
// Sets related.R.Cover appropriately.
func (o *Cover) AddNovels(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Novel) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CoverID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ste\".\"novel\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"cover_id"}),
				strmangle.WhereClause("\"", "\"", 2, novelPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CoverID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &coverR{
			Novels: related,
		}
	} else {
		o.R.Novels = append(o.R.Novels, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &novelR{
				Cover: o,
			}
		} else {
			rel.R.Cover = o
		}
	}
	return nil
}

// SetNovels removes all previously related items of the
// cover replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Cover's Novels accordingly.
// Replaces o.R.Novels with related.
// Sets related.R.Cover's Novels accordingly.
func (o *Cover) SetNovels(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Novel) error {
	query := "update \"ste\".\"novel\" set \"cover_id\" = null where \"cover_id\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Novels {
			queries.SetScanner(&rel.CoverID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Cover = nil
		}

		o.R.Novels = nil
	}
	return o.AddNovels(ctx, exec, insert, related...)
}

// RemoveNovels relationships from objects passed in.
// Removes related items from R.Novels (uses pointer comparison, removal does not keep order)
// Sets related.R.Cover.
func (o *Cover) RemoveNovels(ctx context.Context, exec boil.ContextExecutor, related ...*Novel) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CoverID, nil)
		if rel.R != nil {
			rel.R.Cover = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("cover_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Novels {
			if rel != ri {
				continue
			}

			ln := len(o.R.Novels)
			if ln > 1 && i < ln-1 {
				o.R.Novels[i] = o.R.Novels[ln-1]
			}
			o.R.Novels = o.R.Novels[:ln-1]
			break
		}
	}

	return nil
}

// Covers retrieves all the records using an executor.
func Covers(mods ...qm.QueryMod) coverQuery {
	mods = append(mods, qm.From("\"ste\".\"cover\""))
	return coverQuery{NewQuery(mods...)}
}

// FindCover retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCover(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Cover, error) {
	coverObj := &Cover{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ste\".\"cover\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, coverObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from cover")
	}

	return coverObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Cover) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no cover provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(coverColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	coverInsertCacheMut.RLock()
	cache, cached := coverInsertCache[key]
	coverInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			coverColumns,
			coverColumnsWithDefault,
			coverColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(coverType, coverMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(coverType, coverMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ste\".\"cover\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ste\".\"cover\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into cover")
	}

	if !cached {
		coverInsertCacheMut.Lock()
		coverInsertCache[key] = cache
		coverInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Cover.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Cover) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	coverUpdateCacheMut.RLock()
	cache, cached := coverUpdateCache[key]
	coverUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			coverColumns,
			coverPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update cover, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ste\".\"cover\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, coverPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(coverType, coverMapping, append(wl, coverPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update cover row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for cover")
	}

	if !cached {
		coverUpdateCacheMut.Lock()
		coverUpdateCache[key] = cache
		coverUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q coverQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for cover")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for cover")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CoverSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), coverPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ste\".\"cover\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, coverPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in cover slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all cover")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Cover) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no cover provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(coverColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	coverUpsertCacheMut.RLock()
	cache, cached := coverUpsertCache[key]
	coverUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			coverColumns,
			coverColumnsWithDefault,
			coverColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			coverColumns,
			coverPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert cover, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(coverPrimaryKeyColumns))
			copy(conflict, coverPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ste\".\"cover\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(coverType, coverMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(coverType, coverMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert cover")
	}

	if !cached {
		coverUpsertCacheMut.Lock()
		coverUpsertCache[key] = cache
		coverUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Cover record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Cover) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Cover provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), coverPrimaryKeyMapping)
	sql := "DELETE FROM \"ste\".\"cover\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from cover")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for cover")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q coverQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no coverQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from cover")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for cover")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CoverSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Cover slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(coverBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), coverPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ste\".\"cover\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, coverPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from cover slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for cover")
	}

	if len(coverAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Cover) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCover(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CoverSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CoverSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), coverPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ste\".\"cover\".* FROM \"ste\".\"cover\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, coverPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CoverSlice")
	}

	*o = slice

	return nil
}

// CoverExists checks if the Cover row exists.
func CoverExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ste\".\"cover\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if cover exists")
	}

	return exists, nil
}
