// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// NovelQueue is an object representing the database table.
type NovelQueue struct {
	NovelID    int         `boil:"novel_id" json:"novel_id" toml:"novel_id" yaml:"novel_id"`
	URL        null.String `boil:"url" json:"url,omitempty" toml:"url" yaml:"url,omitempty"`
	SourceId   null.Int    `boil:"sourceId" json:"sourceId,omitempty" toml:"sourceId" yaml:"sourceId,omitempty"`
	QueuedAt   time.Time   `boil:"queuedAt" json:"queuedAt" toml:"queuedAt" yaml:"queuedAt"`
	Finished   null.Bool   `boil:"finished" json:"finished,omitempty" toml:"finished" yaml:"finished,omitempty"`
	FinishedAt null.Time   `boil:"finishedAt" json:"finishedAt,omitempty" toml:"finishedAt" yaml:"finishedAt,omitempty"`

	R *novelQueueR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L novelQueueL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NovelQueueColumns = struct {
	NovelID    string
	URL        string
	SourceId   string
	QueuedAt   string
	Finished   string
	FinishedAt string
}{
	NovelID:    "novel_id",
	URL:        "url",
	SourceId:   "sourceId",
	QueuedAt:   "queuedAt",
	Finished:   "finished",
	FinishedAt: "finishedAt",
}

// Generated where

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var NovelQueueWhere = struct {
	NovelID    whereHelperint
	URL        whereHelpernull_String
	SourceId   whereHelpernull_Int
	QueuedAt   whereHelpertime_Time
	Finished   whereHelpernull_Bool
	FinishedAt whereHelpernull_Time
}{
	NovelID:    whereHelperint{field: `novel_id`},
	URL:        whereHelpernull_String{field: `url`},
	SourceId:   whereHelpernull_Int{field: `sourceId`},
	QueuedAt:   whereHelpertime_Time{field: `queuedAt`},
	Finished:   whereHelpernull_Bool{field: `finished`},
	FinishedAt: whereHelpernull_Time{field: `finishedAt`},
}

// NovelQueueRels is where relationship names are stored.
var NovelQueueRels = struct {
	Novel string
}{
	Novel: "Novel",
}

// novelQueueR is where relationships are stored.
type novelQueueR struct {
	Novel *Novel
}

// NewStruct creates a new relationship struct
func (*novelQueueR) NewStruct() *novelQueueR {
	return &novelQueueR{}
}

// novelQueueL is where Load methods for each relationship are stored.
type novelQueueL struct{}

var (
	novelQueueColumns               = []string{"novel_id", "url", "sourceId", "queuedAt", "finished", "finishedAt"}
	novelQueueColumnsWithoutDefault = []string{"novel_id", "url", "sourceId", "queuedAt", "finishedAt"}
	novelQueueColumnsWithDefault    = []string{"finished"}
	novelQueuePrimaryKeyColumns     = []string{"novel_id", "queuedAt"}
)

type (
	// NovelQueueSlice is an alias for a slice of pointers to NovelQueue.
	// This should generally be used opposed to []NovelQueue.
	NovelQueueSlice []*NovelQueue
	// NovelQueueHook is the signature for custom NovelQueue hook methods
	NovelQueueHook func(context.Context, boil.ContextExecutor, *NovelQueue) error

	novelQueueQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	novelQueueType                 = reflect.TypeOf(&NovelQueue{})
	novelQueueMapping              = queries.MakeStructMapping(novelQueueType)
	novelQueuePrimaryKeyMapping, _ = queries.BindMapping(novelQueueType, novelQueueMapping, novelQueuePrimaryKeyColumns)
	novelQueueInsertCacheMut       sync.RWMutex
	novelQueueInsertCache          = make(map[string]insertCache)
	novelQueueUpdateCacheMut       sync.RWMutex
	novelQueueUpdateCache          = make(map[string]updateCache)
	novelQueueUpsertCacheMut       sync.RWMutex
	novelQueueUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var novelQueueBeforeInsertHooks []NovelQueueHook
var novelQueueBeforeUpdateHooks []NovelQueueHook
var novelQueueBeforeDeleteHooks []NovelQueueHook
var novelQueueBeforeUpsertHooks []NovelQueueHook

var novelQueueAfterInsertHooks []NovelQueueHook
var novelQueueAfterSelectHooks []NovelQueueHook
var novelQueueAfterUpdateHooks []NovelQueueHook
var novelQueueAfterDeleteHooks []NovelQueueHook
var novelQueueAfterUpsertHooks []NovelQueueHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *NovelQueue) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *NovelQueue) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *NovelQueue) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *NovelQueue) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *NovelQueue) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *NovelQueue) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *NovelQueue) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *NovelQueue) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *NovelQueue) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range novelQueueAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddNovelQueueHook registers your hook function for all future operations.
func AddNovelQueueHook(hookPoint boil.HookPoint, novelQueueHook NovelQueueHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		novelQueueBeforeInsertHooks = append(novelQueueBeforeInsertHooks, novelQueueHook)
	case boil.BeforeUpdateHook:
		novelQueueBeforeUpdateHooks = append(novelQueueBeforeUpdateHooks, novelQueueHook)
	case boil.BeforeDeleteHook:
		novelQueueBeforeDeleteHooks = append(novelQueueBeforeDeleteHooks, novelQueueHook)
	case boil.BeforeUpsertHook:
		novelQueueBeforeUpsertHooks = append(novelQueueBeforeUpsertHooks, novelQueueHook)
	case boil.AfterInsertHook:
		novelQueueAfterInsertHooks = append(novelQueueAfterInsertHooks, novelQueueHook)
	case boil.AfterSelectHook:
		novelQueueAfterSelectHooks = append(novelQueueAfterSelectHooks, novelQueueHook)
	case boil.AfterUpdateHook:
		novelQueueAfterUpdateHooks = append(novelQueueAfterUpdateHooks, novelQueueHook)
	case boil.AfterDeleteHook:
		novelQueueAfterDeleteHooks = append(novelQueueAfterDeleteHooks, novelQueueHook)
	case boil.AfterUpsertHook:
		novelQueueAfterUpsertHooks = append(novelQueueAfterUpsertHooks, novelQueueHook)
	}
}

// One returns a single novelQueue record from the query.
func (q novelQueueQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NovelQueue, error) {
	o := &NovelQueue{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for novel_queue")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all NovelQueue records from the query.
func (q novelQueueQuery) All(ctx context.Context, exec boil.ContextExecutor) (NovelQueueSlice, error) {
	var o []*NovelQueue

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to NovelQueue slice")
	}

	if len(novelQueueAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all NovelQueue records in the query.
func (q novelQueueQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count novel_queue rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q novelQueueQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if novel_queue exists")
	}

	return count > 0, nil
}

// Novel pointed to by the foreign key.
func (o *NovelQueue) Novel(mods ...qm.QueryMod) novelQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.NovelID),
	}

	queryMods = append(queryMods, mods...)

	query := Novels(queryMods...)
	queries.SetFrom(query.Query, "\"ste\".\"novel\"")

	return query
}

// LoadNovel allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (novelQueueL) LoadNovel(ctx context.Context, e boil.ContextExecutor, singular bool, maybeNovelQueue interface{}, mods queries.Applicator) error {
	var slice []*NovelQueue
	var object *NovelQueue

	if singular {
		object = maybeNovelQueue.(*NovelQueue)
	} else {
		slice = *maybeNovelQueue.(*[]*NovelQueue)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &novelQueueR{}
		}
		args = append(args, object.NovelID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &novelQueueR{}
			}

			for _, a := range args {
				if a == obj.NovelID {
					continue Outer
				}
			}

			args = append(args, obj.NovelID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`ste.novel`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Novel")
	}

	var resultSlice []*Novel
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Novel")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for novel")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for novel")
	}

	if len(novelQueueAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Novel = foreign
		if foreign.R == nil {
			foreign.R = &novelR{}
		}
		foreign.R.NovelQueues = append(foreign.R.NovelQueues, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.NovelID == foreign.ID {
				local.R.Novel = foreign
				if foreign.R == nil {
					foreign.R = &novelR{}
				}
				foreign.R.NovelQueues = append(foreign.R.NovelQueues, local)
				break
			}
		}
	}

	return nil
}

// SetNovel of the novelQueue to the related item.
// Sets o.R.Novel to related.
// Adds o to related.R.NovelQueues.
func (o *NovelQueue) SetNovel(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Novel) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ste\".\"novel_queue\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"novel_id"}),
		strmangle.WhereClause("\"", "\"", 2, novelQueuePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.NovelID, o.QueuedAt}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.NovelID = related.ID
	if o.R == nil {
		o.R = &novelQueueR{
			Novel: related,
		}
	} else {
		o.R.Novel = related
	}

	if related.R == nil {
		related.R = &novelR{
			NovelQueues: NovelQueueSlice{o},
		}
	} else {
		related.R.NovelQueues = append(related.R.NovelQueues, o)
	}

	return nil
}

// NovelQueues retrieves all the records using an executor.
func NovelQueues(mods ...qm.QueryMod) novelQueueQuery {
	mods = append(mods, qm.From("\"ste\".\"novel_queue\""))
	return novelQueueQuery{NewQuery(mods...)}
}

// FindNovelQueue retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNovelQueue(ctx context.Context, exec boil.ContextExecutor, novelID int, queuedAt time.Time, selectCols ...string) (*NovelQueue, error) {
	novelQueueObj := &NovelQueue{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ste\".\"novel_queue\" where \"novel_id\"=$1 AND \"queuedAt\"=$2", sel,
	)

	q := queries.Raw(query, novelID, queuedAt)

	err := q.Bind(ctx, exec, novelQueueObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from novel_queue")
	}

	return novelQueueObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NovelQueue) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no novel_queue provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(novelQueueColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	novelQueueInsertCacheMut.RLock()
	cache, cached := novelQueueInsertCache[key]
	novelQueueInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			novelQueueColumns,
			novelQueueColumnsWithDefault,
			novelQueueColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(novelQueueType, novelQueueMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(novelQueueType, novelQueueMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ste\".\"novel_queue\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ste\".\"novel_queue\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into novel_queue")
	}

	if !cached {
		novelQueueInsertCacheMut.Lock()
		novelQueueInsertCache[key] = cache
		novelQueueInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the NovelQueue.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NovelQueue) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	novelQueueUpdateCacheMut.RLock()
	cache, cached := novelQueueUpdateCache[key]
	novelQueueUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			novelQueueColumns,
			novelQueuePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update novel_queue, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ste\".\"novel_queue\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, novelQueuePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(novelQueueType, novelQueueMapping, append(wl, novelQueuePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update novel_queue row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for novel_queue")
	}

	if !cached {
		novelQueueUpdateCacheMut.Lock()
		novelQueueUpdateCache[key] = cache
		novelQueueUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q novelQueueQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for novel_queue")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for novel_queue")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NovelQueueSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), novelQueuePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ste\".\"novel_queue\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, novelQueuePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in novelQueue slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all novelQueue")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NovelQueue) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no novel_queue provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(novelQueueColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	novelQueueUpsertCacheMut.RLock()
	cache, cached := novelQueueUpsertCache[key]
	novelQueueUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			novelQueueColumns,
			novelQueueColumnsWithDefault,
			novelQueueColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			novelQueueColumns,
			novelQueuePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert novel_queue, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(novelQueuePrimaryKeyColumns))
			copy(conflict, novelQueuePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ste\".\"novel_queue\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(novelQueueType, novelQueueMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(novelQueueType, novelQueueMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert novel_queue")
	}

	if !cached {
		novelQueueUpsertCacheMut.Lock()
		novelQueueUpsertCache[key] = cache
		novelQueueUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single NovelQueue record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NovelQueue) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NovelQueue provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), novelQueuePrimaryKeyMapping)
	sql := "DELETE FROM \"ste\".\"novel_queue\" WHERE \"novel_id\"=$1 AND \"queuedAt\"=$2"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from novel_queue")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for novel_queue")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q novelQueueQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no novelQueueQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from novel_queue")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for novel_queue")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NovelQueueSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NovelQueue slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(novelQueueBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), novelQueuePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ste\".\"novel_queue\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, novelQueuePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from novelQueue slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for novel_queue")
	}

	if len(novelQueueAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NovelQueue) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNovelQueue(ctx, exec, o.NovelID, o.QueuedAt)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NovelQueueSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NovelQueueSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), novelQueuePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ste\".\"novel_queue\".* FROM \"ste\".\"novel_queue\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, novelQueuePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in NovelQueueSlice")
	}

	*o = slice

	return nil
}

// NovelQueueExists checks if the NovelQueue row exists.
func NovelQueueExists(ctx context.Context, exec boil.ContextExecutor, novelID int, queuedAt time.Time) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ste\".\"novel_queue\" where \"novel_id\"=$1 AND \"queuedAt\"=$2 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, novelID, queuedAt)
	}

	row := exec.QueryRowContext(ctx, sql, novelID, queuedAt)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if novel_queue exists")
	}

	return exists, nil
}
